name: Monthly GitHub Metrics Report

on:
  schedule:
    - cron: "59 23 * * *"  # Runs every day at 23:59 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect_metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default token

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests pandas tabulate  # ✅ Ensure `tabulate` is installed

      - name: Determine Report Date
        run: |
          # Get yesterday's date in YYYY-MM-DD format
          REPORT_DATE=$(date -d "yesterday" +"%Y-%m-%d")

          # If today is March 1st, use February 28 (or 29 if leap year)
          if [ "$(date +%m)" == "03" ] && [ "$(date +%-d)" == "1" ]; then
            REPORT_DATE=$(date -d "last day of last month" +"%Y-%m-%d")
          fi

          echo "REPORT_DATE=$REPORT_DATE" >> $GITHUB_ENV

      - name: Run GitHub Metrics Script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPORT_DATE: ${{ env.REPORT_DATE }}
        run: python github_metrics.py "$REPORT_DATE"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add open_source_metrics.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated Open Source Metrics for ${{ env.REPORT_DATE }}"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
