name: Update Metrics Webpage & Dashboard

on:
  push:
    paths:
      - metrics_history.json
      - dashboard/**
      - open_source_metrics.md
      - .github/workflows/update_page.yml
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # --- Dashboard Build ---
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Dashboard
        working-directory: ./dashboard
        run: |
          npm install
          npm run build

      - name: Copy metrics_history.json into dashboard build
        run: cp metrics_history.json dashboard/build/metrics_history.json

      # --- Markdown to HTML for Main Page ---
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML (main page)
        run: pandoc open_source_metrics.md -o index.html

      # --- Prepare Deployment Directory ---
      - name: Prepare Deployment Directory
        run: |
          mkdir deploy
          mv index.html deploy/
          cp -r dashboard/build deploy/dashboard

      # --- Deploy to GitHub Pages ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
